services:

  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  init:
    image: busybox:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo

  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.7
    environment:
      - ENDPOINT=tempo:4317
      - TEMPO_X_SCOPE_ORGID=test
    restart: always
    depends_on:
      - tempo

  k6-tracing-2:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.7
    environment:
      - ENDPOINT=tempo:4317
      - TEMPO_X_SCOPE_ORGID=test2
    restart: always
    depends_on:
      - tempo

  grafana:
    image: grafana/grafana:12.0.0
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
    ports:
      - "3000:3000"

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=tempo
      - MINIO_SECRET_KEY=supersecret
      - MINIO_KMS_KES_ENDPOINT=https://kes:7373
      - MINIO_KMS_KES_KEY_NAME=my-minio-key
      - MINIO_KMS_AUTO_ENCRYPTION=off
      - MINIO_KMS_KES_CERT_FILE=/root/.minio/certs/minio.crt
      - MINIO_KMS_KES_KEY_FILE=/root/.minio/certs/minio.key
      - MINIO_KMS_KES_CAPATH=/root/.minio/certs/CAs/kes_ca.crt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      retries: 12
      start_period: 5s
    ports:
      - "9001:9001"
    # entrypoint:
    #   - sh
    #   - -euc
    #   - mkdir -p /data/tempo && minio server /data --console-address ':9001'
    entrypoint:
      - minio
      - server
      - /data
      - --console-address
      - ":9001"
    volumes:
      - ./minio/certs:/root/.minio/certs:ro
    depends_on:
      - kes

  kes:
    image: minio/kes:latest
    container_name: kes
    restart: unless-stopped
    command: server --config /etc/kes/config.yaml
    volumes:
      - ./kes.yaml:/etc/kes/config.yaml:ro
      - ./kes/certs:/etc/kes/certs:ro
      - ./kes/keys:/etc/kes/keys
    ports:
      - "7373:7373"

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    environment:
      - GRPC_TRACE=api
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    depends_on:
      minio:
        condition: service_healthy
      init:
        condition: service_completed_successfully
