target: all
multitenancy_enabled: true
stream_over_http_enabled: true
server:
  http_listen_port: 3200
  log_level: info

query_frontend:
  multi_tenant_queries_enabled: true
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
    metadata_slo:
        duration_slo: 5s
        throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "tempo:4317"
        http:
          endpoint: "tempo:4318"

ingester:
  max_block_duration: 1m   # flush headblocks to S3 every 1 minute

compactor:
  compaction:
    block_retention: 2m   # blocks older than 2m are compacted

metrics_generator:

storage:
  trace:
    backend: s3                        # backend configuration to use
    wal:
      path: /var/tempo/wal             # where to store the wal locally
    s3:
      bucket: tempo                    # how to store data in s3
      endpoint: minio:9000
      access_key: tempo
      secret_key: supersecret
      insecure: true
      sse:
        type: SSE-KMS
        kms_key_id: my-minio-key
      tags: 
        creator: tempo
      # For using AWS, select the appropriate regional endpoint and region
      # endpoint: s3.dualstack.us-west-2.amazonaws.com
      # region: us-west-2

overrides:
  defaults:
    metrics_generator:
